from __future__ import annotations

from pathlib import Path


def write_env_files(project_root: Path) -> None:
    agents_dir = project_root / ".agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    env_sh = agents_dir / "env.sh"
    env_ps1 = agents_dir / "env.ps1"
    env_sh.write_text(
        "# Generated by CocoaSkill. Do not edit.\n"
        "CSK_PROJECT_ROOT=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/..\" && pwd)\"\n"
        "export CSK_PROJECT_ROOT\n"
        "export PATH=\"$CSK_PROJECT_ROOT/.agents/bin:$PATH\"\n",
        encoding="utf-8",
    )
    env_ps1.write_text(
        "# Generated by CocoaSkill. Do not edit.\n"
        "$CskAgentsDir = Split-Path -Parent $MyInvocation.MyCommand.Path\n"
        "$CskProjectRoot = Split-Path -Parent $CskAgentsDir\n"
        "$env:CSK_PROJECT_ROOT = $CskProjectRoot\n"
        "$env:PATH = \"$CskProjectRoot\\.agents\\bin;$env:PATH\"\n",
        encoding="utf-8",
    )

