from __future__ import annotations

from pathlib import Path

from . import shell_approvals


def write_env_files(project_root: Path, *, approval_root: Path | None = None) -> None:
    agents_dir = project_root / ".agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    env_sh = agents_dir / "env.sh"
    env_ps1 = agents_dir / "env.ps1"
    approved_agents = (approval_root or project_root) / ".agents"
    # The script locates itself under bash (BASH_SOURCE), zsh (prompt %N
    # expansion), and falls back to $0 elsewhere; zsh leaves BASH_SOURCE unset,
    # which previously resolved the project root from the caller's CWD.
    _write_approved(
        env_sh,
        "# Generated by CocoaSkill. Do not edit.\n"
        "if [ -n \"${BASH_SOURCE:-}\" ]; then\n"
        "  _csk_env_path=\"${BASH_SOURCE[0]}\"\n"
        "elif [ -n \"${ZSH_VERSION:-}\" ]; then\n"
        "  _csk_env_path=\"${(%):-%N}\"\n"
        "else\n"
        "  _csk_env_path=\"$0\"\n"
        "fi\n"
        "CSK_PROJECT_ROOT=\"$(cd \"$(dirname \"$_csk_env_path\")/..\" && pwd)\"\n"
        "unset _csk_env_path\n"
        "export CSK_PROJECT_ROOT\n"
        "export PATH=\"$CSK_PROJECT_ROOT/.agents/bin:$PATH\"\n",
        approved_agents / "env.sh",
    )
    _write_approved(
        env_ps1,
        "# Generated by CocoaSkill. Do not edit.\n"
        "$CskAgentsDir = Split-Path -Parent $MyInvocation.MyCommand.Path\n"
        "$CskProjectRoot = Split-Path -Parent $CskAgentsDir\n"
        "$env:CSK_PROJECT_ROOT = $CskProjectRoot\n"
        "$env:PATH = \"$CskProjectRoot\\.agents\\bin;$env:PATH\"\n",
        approved_agents / "env.ps1",
    )


def write_global_env_files(
    csk_home: Path,
    *,
    activation_home: Path | None = None,
) -> None:
    global_dir = csk_home / "global"
    bin_dir = global_dir / "bin"
    activation_global_dir = (
        csk_home if activation_home is None else activation_home
    ) / "global"
    global_dir.mkdir(parents=True, exist_ok=True)
    bin_dir.mkdir(parents=True, exist_ok=True)
    env_sh = global_dir / "env.sh"
    env_ps1 = global_dir / "env.ps1"
    _write_approved(
        env_sh,
        "# Generated by CocoaSkill. Do not edit.\n"
        f"export CSK_GLOBAL_ROOT={_sh_quote(str(activation_global_dir))}\n"
        'export PATH="$CSK_GLOBAL_ROOT/bin:$PATH"\n',
        activation_global_dir / "env.sh",
    )
    _write_approved(
        env_ps1,
        "# Generated by CocoaSkill. Do not edit.\n"
        f"$env:CSK_GLOBAL_ROOT = {_ps_quote(str(activation_global_dir))}\n"
        '$env:PATH = "$env:CSK_GLOBAL_ROOT\\bin;$env:PATH"\n',
        activation_global_dir / "env.ps1",
    )


def _sh_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _ps_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _write_approved(path: Path, content: str, approval_path: Path) -> None:
    data = content.encode("utf-8")
    path.write_bytes(data)
    shell_approvals.record({approval_path: shell_approvals.digest(data)})
