from __future__ import annotations

from pathlib import Path


def write_env_files(project_root: Path) -> None:
    agents_dir = project_root / ".agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    env_sh = agents_dir / "env.sh"
    env_ps1 = agents_dir / "env.ps1"
    # The script locates itself under bash (BASH_SOURCE), zsh (prompt %N
    # expansion), and falls back to $0 elsewhere; zsh leaves BASH_SOURCE unset,
    # which previously resolved the project root from the caller's CWD.
    env_sh.write_text(
        "# Generated by CocoaSkill. Do not edit.\n"
        "if [ -n \"${BASH_SOURCE:-}\" ]; then\n"
        "  _csk_env_path=\"${BASH_SOURCE[0]}\"\n"
        "elif [ -n \"${ZSH_VERSION:-}\" ]; then\n"
        "  _csk_env_path=\"${(%):-%N}\"\n"
        "else\n"
        "  _csk_env_path=\"$0\"\n"
        "fi\n"
        "CSK_PROJECT_ROOT=\"$(cd \"$(dirname \"$_csk_env_path\")/..\" && pwd)\"\n"
        "unset _csk_env_path\n"
        "export CSK_PROJECT_ROOT\n"
        "export PATH=\"$CSK_PROJECT_ROOT/.agents/bin:$PATH\"\n",
        encoding="utf-8",
    )
    env_ps1.write_text(
        "# Generated by CocoaSkill. Do not edit.\n"
        "$CskAgentsDir = Split-Path -Parent $MyInvocation.MyCommand.Path\n"
        "$CskProjectRoot = Split-Path -Parent $CskAgentsDir\n"
        "$env:CSK_PROJECT_ROOT = $CskProjectRoot\n"
        "$env:PATH = \"$CskProjectRoot\\.agents\\bin;$env:PATH\"\n",
        encoding="utf-8",
    )


def write_global_env_files(csk_home: Path) -> None:
    global_dir = csk_home / "global"
    bin_dir = global_dir / "bin"
    global_dir.mkdir(parents=True, exist_ok=True)
    bin_dir.mkdir(parents=True, exist_ok=True)
    env_sh = global_dir / "env.sh"
    env_ps1 = global_dir / "env.ps1"
    env_sh.write_text(
        "# Generated by CocoaSkill. Do not edit.\n"
        f"export CSK_GLOBAL_ROOT={_sh_quote(str(global_dir))}\n"
        'export PATH="$CSK_GLOBAL_ROOT/bin:$PATH"\n',
        encoding="utf-8",
    )
    env_ps1.write_text(
        "# Generated by CocoaSkill. Do not edit.\n"
        f"$env:CSK_GLOBAL_ROOT = {_ps_quote(str(global_dir))}\n"
        '$env:PATH = "$env:CSK_GLOBAL_ROOT\\bin;$env:PATH"\n',
        encoding="utf-8",
    )


def _sh_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _ps_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"
